spring:
  application:
    name: games

server:
  port: 8080

logging:
  file:
    name: logs/rplace.log  # relative to project root or working directory
  logback:
    rollingpolicy:
      max-file-size: 10MB
      #max-history: 7        # keep up to 7 archived logs
      total-size-cap: 100MB # optional: delete old logs after 100MB
  level:
    root: info
    cder.rplace: info

rplace:
  grid:
    width: 100
    height: 100
    scale: 5
  # rate limiting
  cooldown-millis: 120000
  max-pixels-per-batch: 20
  # update the image every 2 seconds
  image-update-frequency: 2000
  # snapshots
  snapshot-frequency: 120000
  snapshot-dir: snapshots
  # reload most recent snapshot upon startup?
  reload-snapshot: true
  colors:
    0: "#6d001a"
    1: "#be0039"
    2: "#ff4500"
    3: "#ffa800"
    4: "#ffd635"
    5: "#fff8b8"
    6: "#00a368"
    7: "#00cc78"
    8: "#7eed56"
    9: "#00756f"
    10: "#009eaa"
    11: "#00ccc0"
    12: "#2450a4"
    13: "#3690ea"
    14: "#51e9f4"
    15: "#493ac1"
    16: "#6a5cff"
    17: "#94b3ff"
    18: "#811e9f"
    19: "#b44ac0"
    20: "#e4abff"
    21: "#de107f"
    22: "#ff3881"
    23: "#ff99aa"
    24: "#6d482f"
    25: "#9c6926"
    26: "#ffb470"
    27: "#000000"
    28: "#515252"
    29: "#898d90"
    30: "#d4d7d9"
    31: "#ffffff"
