spring:
  application:
    name: games

server:
  port: 8080

rplace:
  grid:
    width: 100
    height: 100
    scale: 5
  cooldown-millis: 120000
  max-pixels-per-batch: 20
  # update the image every 2 seconds
  image-update-frequency: 2000
  # reload most recent snapshot
  reload-snapshot: true
  snapshot-dir: images/snapshots
